export interface PineHolding {
  symbol: string;
  quantity: number;
  targetPct: number;
}

// TradingView allows 40 request.security calls per script; keep headroom.
export const PINE_MAX_HOLDINGS = 38;

const DEFAULT_TITLE = 'Omnigalactic Portfolio Allocation';
const DEFAULT_DRIFT_THRESHOLD_PCT = 5;

const esc = (s: string): string => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

const num = (n: number): string => String(n);

/**
 * Emits a self-contained Pine Script v6 indicator for the given holdings.
 * Straight-line per-holding variables (price0, val0, ...) instead of arrays
 * so the script stays readable and avoids Pine loop/scope pitfalls.
 */
export function generatePortfolioPine(
  holdings: PineHolding[],
  opts?: { title?: string; driftThresholdPct?: number }
): string {
  if (holdings.length === 0) {
    throw new Error('Add at least one holding to generate a Pine script.');
  }
  if (holdings.length > PINE_MAX_HOLDINGS) {
    throw new Error(
      `Pine scripts support at most ${PINE_MAX_HOLDINGS} holdings (TradingView request.security budget).`
    );
  }
  const title = opts?.title ?? DEFAULT_TITLE;
  const threshold = opts?.driftThresholdPct ?? DEFAULT_DRIFT_THRESHOLD_PCT;
  // Avoid float artifacts (e.g. 33.33 * 3) leaking into the emitted literal.
  const targetTotal = Math.round(holdings.reduce((sum, h) => sum + h.targetPct, 0) * 100) / 100;

  const lines: string[] = [
    '// Generated by the Omnigalactic Invest tab. Do not edit by hand.',
    '// How to use: open any chart on TradingView, open the "Pine Editor" panel,',
    '// paste this entire script, and click "Add to chart".',
    '// This script is a snapshot of your holdings. After editing them in the',
    '// app, press the "TradingView script" button again to recompute it.',
    '',
    '//@version=6',
    `indicator("${esc(title)}", overlay=false)`,
    '',
    `driftThreshold = ${num(threshold)}`,
    '',
  ];

  holdings.forEach((h, i) => {
    lines.push(`price${i} = request.security("${esc(h.symbol)}", timeframe.period, close)`);
    lines.push(`val${i} = ${num(h.quantity)} * price${i}`);
  });
  lines.push('');
  // nz() keeps holdings whose data hasn't loaded out of the total; their own
  // val/weight stay na so they render as pending instead of a false 0.
  lines.push(`total = ${holdings.map((_, i) => `nz(val${i})`).join(' + ')}`);
  lines.push('');
  holdings.forEach((h, i) => {
    lines.push(`w${i} = total > 0 ? val${i} / total * 100 : na`);
    lines.push(`d${i} = w${i} - ${num(h.targetPct)}`);
  });
  lines.push('');
  lines.push('maxAbsDrift = 0.0');
  holdings.forEach((_, i) => {
    lines.push(`maxAbsDrift := math.max(maxAbsDrift, math.abs(nz(d${i})))`);
  });
  lines.push('');
  lines.push('plot(total, "Portfolio value", color=color.teal, linewidth=2)');
  lines.push('');
  lines.push(
    `var table t = table.new(position.top_right, 7, ${holdings.length + 2}, ` +
      'bgcolor=color.new(color.black, 80), border_width=1, border_color=color.new(color.gray, 60))'
  );
  lines.push('if barstate.islast');
  ['Symbol', 'Qty', 'Price', 'Value', 'Weight %', 'Target %', 'Drift'].forEach((label, col) => {
    lines.push(
      `    table.cell(t, ${col}, 0, "${label}", text_color=color.white, bgcolor=color.new(color.gray, 40))`
    );
  });
  holdings.forEach((h, i) => {
    const row = i + 1;
    lines.push(`    table.cell(t, 0, ${row}, "${esc(h.symbol)}", text_color=color.white)`);
    lines.push(`    table.cell(t, 1, ${row}, "${num(h.quantity)}", text_color=color.white)`);
    lines.push(
      `    table.cell(t, 2, ${row}, na(price${i}) ? "…" : str.tostring(price${i}, '#.##'), text_color=color.white)`
    );
    lines.push(
      `    table.cell(t, 3, ${row}, na(val${i}) ? "…" : str.tostring(val${i}, '#.##'), text_color=color.white)`
    );
    lines.push(
      `    table.cell(t, 4, ${row}, na(w${i}) ? "…" : str.tostring(w${i}, '#.#'), text_color=color.white)`
    );
    lines.push(`    table.cell(t, 5, ${row}, "${num(h.targetPct)}", text_color=color.white)`);
    lines.push(
      `    table.cell(t, 6, ${row}, na(d${i}) ? "…" : str.tostring(d${i}, '#.#'), text_color=color.white, ` +
        `bgcolor=not na(d${i}) and math.abs(d${i}) > driftThreshold ? color.new(color.red, 60) : color.new(color.gray, 70))`
    );
  });
  const totalRow = holdings.length + 1;
  const totalBg = 'bgcolor=color.new(color.gray, 40)';
  lines.push(`    table.cell(t, 0, ${totalRow}, "TOTAL", text_color=color.white, ${totalBg})`);
  lines.push(`    table.cell(t, 1, ${totalRow}, "", ${totalBg})`);
  lines.push(`    table.cell(t, 2, ${totalRow}, "", ${totalBg})`);
  lines.push(
    `    table.cell(t, 3, ${totalRow}, str.tostring(total, '#.##'), text_color=color.white, ${totalBg})`
  );
  lines.push(
    `    table.cell(t, 4, ${totalRow}, total > 0 ? "100" : "…", text_color=color.white, ${totalBg})`
  );
  lines.push(`    table.cell(t, 5, ${totalRow}, "${num(targetTotal)}", text_color=color.white, ${totalBg})`);
  lines.push(`    table.cell(t, 6, ${totalRow}, "", ${totalBg})`);
  lines.push('');
  // alertcondition() only accepts const strings, so the message is baked in
  // at generation time.
  lines.push(
    'alertcondition(maxAbsDrift > driftThreshold, title="Portfolio drift alert", ' +
      `message="${esc(`A holding drifted more than ${num(threshold)}% from its target allocation.`)}")`
  );
  return lines.join('\n') + '\n';
}
